personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"

notify = [
  "/Users/tombell/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
  "turn-ended",
]

[projects."/Users/tombell/Code/4ad-companion/companion"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-06-21T07:40:09Z"
source_type = "local"
source = "/Users/tombell/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-20T05:40:57Z"
source_type = "local"
source = "/Users/tombell/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."build-macos-apps@openai-curated"]
enabled = true

[plugins."build-web-apps@openai-curated"]
enabled = true

[plugins."build-ios-apps@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[desktop]
appearanceLightCodeThemeId = "codex"
appearanceDarkCodeThemeId = "tokyo-night"
sansFontSize = 14
usePointerCursors = false
mac-menu-bar-enabled = false
composerEnterBehavior = "cmdIfMultiline"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-create-pull-request-as-draft = true
git-pull-request-merge-method = "squash"
git-show-sidebar-pr-icons = true
git-commit-instructions = "Do not use conventional commits style commit messages."
conversationDetailMode = "STEPS_COMMANDS"
dictationDictionary = []
notifications-turn-mode = "off"
ambient-suggestions-enabled = true
show-context-window-usage = true

[desktop.appearanceLightChromeTheme]
accent = "#0169cc"
contrast = 45
ink = "#0d0d0d"
opaqueWindows = true
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = '"Iosevka Custom"'
ui = "Inter"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#751ed9"

[desktop.appearanceDarkChromeTheme]
accent = "#3d59a1"
contrast = 45
ink = "#a9b1d6"
opaqueWindows = true
surface = "#1a1b26"

[desktop.appearanceDarkChromeTheme.fonts]
code = '"Iosevka Custom"'
ui = "Inter"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#449dab"
diffRemoved = "#914c54"
skill = "#9d7cd8"

[desktop.open-in-target-preferences]
global = "fileManager"

[features]
workspace_dependencies = true
js_repl = false
multi_agent = true
memories = true

[[skills.config]]
name = "build-web-apps:frontend-testing-debugging"
enabled = false

[[skills.config]]
name = "build-web-apps:shadcn"
enabled = false

[[skills.config]]
name = "build-web-apps:stripe-best-practices"
enabled = false

[[skills.config]]
name = "build-web-apps:supabase-postgres-best-practices"
enabled = false

[[skills.config]]
name = "build-ios-apps:ios-debugger-agent"
enabled = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/tombell/.codex"
CODEX_HOME = "/Users/tombell/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "2c20141b13bec5a64cd2874d8e2df011430d5b1a70e4f5425aa10d01743311a8"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.616.51431"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[memories]
generate_memories = true
use_memories = true
disable_on_external_context = true
