$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

bindel = , XF86AudioMute, exec, $osdclient --output-volume mute-toggle
bindel = , XF86AudioLowerVolume, exec, $osdclient --output-volume lower
bindel = , XF86AudioRaiseVolume,exec, $osdclient --output-volume raise
bindel = , XF86AudioMicMute, exec, $osdclient --input-volume mute-toggle
bindel = , XF86MonBrightnessDown, exec, $osdclient --brightness lower
bindel = , XF86MonBrightnessUp, exec, $osdclient --brightness raise
