window:
  dynamic_padding: true
  padding:
    x: 15
    y: 10
  decorations: Buttonless

font:
  size: 11.0
  normal:
    family: Iosevka Term SS08
    style: Regular
  bold:
    family: Iosevka Term SS08
    style: Bold
  italic:
    family: Iosevka Term SS08
    style: Italic
  bold_italic:
    family: Iosevka Term SS08
    style: Bold Italic

draw_bold_text_with_bright_colors: true

custom_cursor_colors: false

colors:
  primary:
    background: '#1e1d2f'
    foreground: '#d9e0ee'
  cursor:
    text: '#1e1d2f'
    cursor: '#f5e0dc'
  normal:
    black:   '#6e6c7e'
    red:     '#f28fad'
    green:   '#abe9b3'
    yellow:  '#fae3b0'
    blue:    '#96cdfb'
    magenta: '#f5c2e7'
    cyan:    '#89dceb'
    white:   '#d9e0ee'
  bright:
    black:   '#988ba2'
    red:     '#f28fad'
    green:   '#abe9b3'
    yellow:  '#fae3b0'
    blue:    '#96cdfb'
    magenta: '#f5c2e7'
    cyan:    '#89dceb'
    white:   '#d9e0ee'
  indexed_colors:
    - { index: 16, color: '0xf8bd96' }
    - { index: 17, color: '0xf5e0dc' }

key_bindings:
  - { key: Key3, mods: Alt, chars: "#" }
