window:
  dynamic_padding: true
  padding:
    x: 15
    y: 10
  decorations: Buttonless

font:
  size: 11.0
  normal:
    family: Iosevka Term SS08
    style: Regular
  bold:
    family: Iosevka Term SS08
    style: Bold
  italic:
    family: Iosevka Term SS08
    style: Italic
  bold_italic:
    family: Iosevka Term SS08
    style: Bold Italic

draw_bold_text_with_bright_colors: true

custom_cursor_colors: false

colors:
  selection:
    text: "#f4f4f4"
    background: "#454d95"
  primary:
    background: "#2c2e34"
    foreground: "#e2e2e3"
  normal:
    black: "#2c2e34"
    red: "#fc5d7c"
    green: "#9ed072"
    yellow: "#e7c664"
    blue: "#76cce0"
    magenta: "#b39df3"
    cyan: "#f39660"
    white: "#e2e2e3"
  bright:
    black: "#2c2e34"
    red: "#fc5d7c"
    green: "#9ed072"
    yellow: "#e7c664"
    blue: "#76cce0"
    magenta: "#b39df3"
    cyan: "#f39660"
    white: "#e2e2e3"

key_bindings:
  - { key: Key3, mods: Alt, chars: "#" }
