import:
  - ~/.config/alacritty/themes/catppuccin-frappe.yml
  # - ~/.config/alacritty/themes/catppuccin-macchiato.yml
  # - ~/.config/alacritty/themes/catppuccin-mocha.yml

window:
  option_as_alt: Both
  padding:
    x: 15
    y: 15
  decorations: buttonless

font:
  size: 11.0
  normal:
    family: Iosevka NFM
    style: Regular
  bold:
    family: Iosevka NFM
    style: Bold
  italic:
    family: Iosevka NFM
    style: Italic
  bold_italic:
    family: Iosevka NFM
    style: Bold Italic

draw_bold_text_with_bright_colors: true

scrolling:
  history: 5000

key_bindings:
  - { key: Key3, mods: Alt, chars: "#" }
