#!/usr/bin/env bash
set -e

DOTFILES="${HOME}/.dotfiles"

###############################################################################
# HOMEBREW
###############################################################################

echo "==> Installing homebrew formulae and casks..."
brew bundle --file "${DOTFILES}/tag-macos/Brewfile"

###############################################################################
# RCM
###############################################################################

echo "==> Installing dotfiles..."
rcup -d "${HOME}/.dotfiles" \
     -t macos \
     -S karabiner \
     -x bin -x Brewfile -x LICENSE -x README.md -x install

###############################################################################
# SETTINGS
###############################################################################

echo "==> Setting macOS defaults..."

###############################################################################
# SOUND
###############################################################################

# Play feedback when volume is changed
defaults write NSGlobalDomain com.apple.sound.beep.feedback -int 1

###############################################################################
# APPEARANCE
###############################################################################

# Sidebar icon size
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

# Show scroll bars
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"

###############################################################################
# CONTROL CENTRE
###############################################################################

# Show date
defaults write com.apple.menuextra.clock ShowDate -int 2

# Show the day of the week
defaults write com.apple.menuextra.clock ShowDayOfWeek -int 0

###############################################################################
# DESKTOP AND DOCK
###############################################################################

# Autohide
defaults write com.apple.dock autohide -int 1

# Recent applications
defaults write com.apple.dock show-recents -int 0

# Icon size
defaults write com.apple.dock tilesize -int 34

# Resizing
defaults write com.apple.dock size-immutable -int 1

# Click wallpaper to reveal desktop
defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -int 0

# Show widgets on desktop
defaults write com.apple.WindowManager StandardHideWidgets -int 1

# Show widgets in stage manager
defaults write com.apple.WindowManager StageManagerHideWidgets -int 1

# Automatically rearrange spaces based on most recent use
defaults write com.apple.dock mru-spaces -int 0

# Bottom right hot corner
defaults write com.apple.dock wvous-br-corner -int 1
defaults write com.apple.dock wvous-br-modifier -int 0

###############################################################################
# LOCK SCREEN
###############################################################################

# Start screen saver when inactive
defaults -currentHost write com.apple.screensaver idleTime -int 0

###############################################################################
# KEYBOARD
###############################################################################

# Press and hold
defaults write NSGlobalDomain ApplePressAndHoldEnabled -int 0

# Full keyboard control in dialogs
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Correct spelling automatically
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -int 0

# Capitalise words automatically
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -int 0

# Show inline predictive text
defaults write NSGlobalDomain NSAutomaticInlinePredictionEnabled -int 0

# Add full stop with double-space
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -int 0

# Smart quotes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -int 0

# Smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -int 0

###############################################################################
# TRACKPAD
###############################################################################

# Tap to click
# defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Natural scrolling
# defaults write NSGlobalDomain com.apple.swipescrolldirection -int 0

###############################################################################
# FINDER
###############################################################################

# Show hard disks on the desktop
defaults write com.apple.finder ShowHardDrivesOnDesktop -int 0

# Show external disks on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -int 0

# Show CDs, DVDs, and iPods on the desktop
defaults write com.apple.finder ShowRemovableMediaOnDesktop -int 0

# Show connected servers on the desktop
defaults write com.apple.finder ShowMountedServersOnDesktop -int 0

# New Finder windows show
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -int 1

# Show warning before changing an extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -int 0

# Show library folder
chflags nohidden ~/Library

# Preferred view style
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

###############################################################################
# RESTART APPS
###############################################################################

killall Dock
killall Finder
