# vim: set ft=ruby:

# ------------------------------------------------------------------------------
# TAPS
# ------------------------------------------------------------------------------

tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "thoughtbot/formulae"
tap "tombell/formulae"

# ------------------------------------------------------------------------------
# FORMULAE
# ------------------------------------------------------------------------------

brew "fzf"
brew "neovim"
brew "ripgrep"
brew "thoughtbot/formulae/rcm"
brew "tmux"
brew "tombell/formulae/lock"
brew "tombell/formulae/skbd"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# ------------------------------------------------------------------------------
# CASKS
# ------------------------------------------------------------------------------

cask "1password"
cask "appcleaner"
cask "discord"
cask "font-iosevka-ss08"
cask "google-chrome"
cask "iterm2"
cask "mpv"
cask "paragon-ntfs"
cask "soundsource"
cask "telegram"
cask "the-unarchiver"
cask "tombell/formulae/stark"
