# vim: set ft=ruby:

tap "homebrew/cask-fonts"
tap "starkwm/formulae"
tap "thoughtbot/formulae"
tap "tombell/formulae"

brew "fzf"
brew "git"
brew "go"
brew "gomodifytags"
brew "gopls"
brew "lock"
brew "neovim"
brew "nodenv"
brew "rbenv"
brew "rbenv-gemset"
brew "rcm"
brew "ripgrep"
brew "skbd"
brew "stylua"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "alacritty"
cask "appcleaner"
cask "discord"
cask "font-iosevka-ss08"
cask "google-chrome"
cask "logi-options-plus"
cask "mpv"
# cask "paragon-ntfs"
cask "soundsource"
cask "stark"
cask "telegram"
cask "the-unarchiver"

if File.exist? "/tmp/work"
  tap "heroku/brew"

  brew "git-lfs"
  brew "heroku"
  brew "postgresql@14"
  brew "redis"
  # brew "watchman"

  # cask "adoptopenjdk8"
  # cask "android-studio"
  cask "chromedriver"
  # cask "paw"
  # cask "postico"
  cask "slack"
  cask "visual-studio-code"
  cask "zoom"
end
