#!/usr/bin/env bash
set -e

OS=$(uname)

if [[ $OS == "Darwin" ]]; then
  echo "==> Installing homebrew formulae and casks..."
  brew bundle
fi

echo "==> Installing dotfiles..."
env RCRC=$HOME/.dotfiles/rcrc rcup

defaults write com.apple.dock tilesize -int 36
defaults write com.apple.dock size-immutable -bool yes
killall Dock
