#!/usr/bin/env bash

# remap caps to ctrl
setxkbmap -option ctrl:nocaps

# load xresources
xrdb ~/.Xresources

# set a simple solid colour wallpaper
# hsetroot -solid "#e0af68"

# set wallpaper
feh --bg-scale ~/Pictures/wallpaper.jpg

# start 1password
1password --silent &

# start dunst
dunst &

# wait for cwm to intialise the _NET_ACTIVE_WINDOW property, then start polybar
(
  while ! xprop -root _NET_ACTIVE_WINDOW >/dev/null 2>&1; do
    sleep 0.2
  done

  ~/.config/polybar/launch.sh
) &

# start sxhkd
sxhkd &

# start cwm
exec cwm -c ~/.config/cwm/cwmrc
