#!/bin/sh

if [ -f "$HOME/Pictures/wallpaper.jpg" ]; then
  feh --bg-scale "$HOME/Pictures/wallpaper.jpg"
else
  hsetroot -solid "#414868"
fi

polybar &
dunst &
sxhkd &
picom &
setxkbmap -option ctrl:nocaps

# start cwm
exec cwm -c "$HOME/.config/cwm/cwmrc"
