return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPost", "BufNewFile", "BufWritePre", "VeryLazy" },
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "css",
        "diff",
        "editorconfig",
        "git_config",
        "git_rebase",
        "html",
        "json",
        "latex",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "scss",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
      },
    },
    cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
    main = "nvim-treesitter.configs",
  },
}
