root: ~/Code/tombell

sessions:
  - name: memoir
    root: ./memoir
    windows:
      - name: server
        commands:
          - make watch
      - name: editor

  - name: memoir-app
    root: ./memoir-app
    windows:
      - name: server
        commands:
          - pnpm run dev
      - name: storybook
        commands:
          - pnpm run storybook
      - name: tests
        commands:
          - pnpm test
      - name: editor

  - name: memoir-sveltekit
    root: ./memoir-sveltekit
    windows:
      - name: server
        commands:
          - npm run dev
      - name: storybook
        commands:
          - npm run storybook
      - name: tests
        commands:
          - npm test
      - name: editor
