root: ~/Code/scribblog

sessions:
  - name: scribblog-api
    root: ./api
    windows:
      - name: server
        commands:
          - make watch
      - name: editor

  - name: scribblog-web
    root: ./web
    windows:
      - name: server
        commands:
          - pnpm run dev
      - name: storybook
        commands:
          - pnpm run storybook
      - name: editor
