root: ~/Code/scribblog

sessions:
  - name: scribblog
    root: ./api
    windows:
      - name: server
        commands:
          - make watch
      - name: editor
        commands:
          - nvim .

  - name: scribblog-web
    root: ./web
    windows:
      - name: server
        commands:
          - pnpm run dev
      - name: storybook
        commands:
          - pnpm run storybook
      - name: tests
        commands:
          - pnpm test
      - name: editor
        commands:
          - nvim .
