root: ~/Code/starkwm

sessions:
  - name: stark
    root: ./stark
    windows:
      - name: editor
        commands:
          - nvim .

  - name: skbd
    root: ./skbd
    windows:
      - name: editor
        commands:
          - nvim .

  - name: swm
    root: ./swm
    windows:
      - name: editor
        commands:
          - nvim .
