root: ~/Code

after_stop:
  - fuckoffpuma || true
  - fuckoffruby || true

sessions:
  - name: backstage
    root: ./backstage
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: contractor
    root: ./contractor
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: doorbell
    root: ./doorbell
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: foundations
    root: ./foundations
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: frontdoor
    root: ./frontdoor
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: knock-knock
    root: ./knock-knock
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: ledger
    root: ./ledger
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: letterbox
    root: ./letterbox
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: living
    root: ./living
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: log-book
    root: ./log-book
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: marketing
    root: ./marketing
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: neighbourhood
    root: ./neighbourhood
    windows:
      - name: server
        commands:
          - ./go run
      - name: storybook
      - name: editor

  - name: piggybank
    root: ./piggybank
    windows:
      - name: server
        commands:
          - ./go run
      - name: stripe
      - name: editor

  - name: porch
    root: ./porch
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: switchboard
    root: ./switchboard
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: mobile-app
    root: ./mobile-app
    windows:
      - name: metro
      - name: editor
