root: ~/Code

sessions:
  - name: backstage
    root: ./backstage
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: contractor
    root: ./contractor
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: doorbell
    root: ./doorbell
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: foundations
    root: ./foundations
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: frontdoor
    root: ./frontdoor
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: knock-knock
    root: ./knock-knock
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: ledger
    root: ./ledger
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: letterbox
    root: ./letterbox
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: living
    root: ./living
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: log-book
    root: ./log-book
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: marketing
    root: ./marketing
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: neighbourhood
    root: ./neighbourhood
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: piggybank
    root: ./piggybank
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: porch
    root: ./porch
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor

  - name: switchboard
    root: ./switchboard
    after_start:
      - tmux select-window -t 1
    windows:
      - name: server
        commands:
          - ./go run
      - name: editor
