theme = "tokyonight"

playback_format = """
{status}  {track} • {artists} [{album}]
{genres}
{metadata}
"""

play_icon = ""
pause_icon = ""
liked_icon = ""

border_type = "Rounded"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"

enable_media_control = false
enable_notify = false
