$mainMod = SUPER

bindd = $mainMod, RETURN, Terminal, exec, /usr/bin/ghostty
bindd = $mainMod, SPACE, Launcher, exec, pkill rofi || /usr/bin/rofi -show drun
bindd = $mainMod SHIFT, SPACE, Passwords, exec, /usr/bin/1password
