background {
  monitor =
  color = rgba(26,27,38,1.0)
}

animations {
  enabled = false
}

input-field {
  monitor =
  size = 600, 100
  position = 0, 0
  halign = center
  valign = center

  inner_color = rgba(26,27,38,0.8)
  outer_color = rgba(205,214,244,1.0)
  outline_thickness = 2

  font_family = CaskaydiaMono Nerd Font
  font_color = rgba(205,214,244,1.0)

  placeholder_text = Enter Password
  check_color = rgba(68,157,171,1.0)
  fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>

  rounding = 5
  shadow_passes = 0
  fade_on_empty = false
}
