source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/layers.conf

$mainMod = SUPER

bind = $mainMod, RETURN,      exec, /usr/bin/ghostty
bind = $mainMod, SPACE,       exec, pkill rofi || /usr/bin/rofi -show drun
bind = $mainMod SHIFT, SPACE, exec, /usr/bin/1password

bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, J, swapwindow, d
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, L, swapwindow, r

bind = $mainMod, TAB, cyclenext
bind = $mainMod, TAB, bringactivetotop

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


