# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 1100 800, tag:floating-window

windowrule = tag +floating-window, class:(tlpui|dev.tombell.wiremix|dev.tombell.bluetui|dev.tombell.impala)
windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk), title:^(Choose.*Files?|Open.*Files?|Open Folder|Save.*Files?|Save.*As|Save|All Files)
windowrule = tag +floating-window, class:(org.gnome.NautilusPreviewer)
