return {
  src = "https://github.com/arborist-ts/arborist.nvim",
  data = {
    setup = function()
      require("arborist").setup {
        prefer_wasm = false,
        update_cadence = "manual",
        ensure_installed = {
          "applescript",
          "bash",
          "c",
          "cpp",
          "css",
          "desktop",
          "diff",
          "dockerfile",
          "editorconfig",
          "embedded_template",
          "git_config",
          "git_rebase",
          "gitcommit",
          "gitignore",
          "go",
          "gomod",
          "gosum",
          "gotmpl",
          "gowork",
          "graphql",
          "html",
          "hyprlang",
          "ini",
          "javascript",
          "jsdoc",
          "json",
          "latex",
          "liquid",
          "lua",
          "luadoc",
          "make",
          "markdown",
          "markdown_inline",
          "objc",
          "python",
          "query",
          "regex",
          "ruby",
          "rust",
          "skbdrc",
          "sql",
          "ssh_config",
          "swift",
          "tmux",
          "toml",
          "tsx",
          "typescript",
          "vimdoc",
          "xml",
          "yaml",
          "zig",
          "zsh",
        },
        overrides = {
          applescript = {
            url = "https://github.com/waddie/tree-sitter-applescript",
          },
          skbdrc = {
            url = "https://github.com/starkwm/tree-sitter-skbdrc",
          },
        },
      }
    end,
  },
}
